name : Build And Publish to Nuget
on:
#   push:
#    branches: [ master ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Description'
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SOLUTION_FILE: src\KevinComponent.sln
      NUGET_FILE: src\Kevincomponent\bin\GitHub Release\*.nupkg
    
    steps:    
    - name: Load Repository Files
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
        
    - name: Build Solution
      run: dotnet build $SOLUTION_FILE -c "GitHub Release"
      
    - name: Publish NuGet
      run: dotnet nuget push "$NUGET_FILE" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
