name : Build And Publish to Nuget
on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Description'
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Load Repository Files
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          4.8
          3.1.x
          6.0.x
    - run: echo '${{ steps.stepid.outputs.dotnet-version }}'
    
