name : Build And Publish to Nuget
on:
#   push:
#    branches: [ master ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Description'
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SOLUTION_FILE: src\KevinComponent.sln
    
    steps:
    - name: Load Repository Files
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
        
    - name: Build Solution
      run: dotnet $SOLUTION_FILE -c "GitHub Release"
