name : Build And Publish to Nuget
on:
#   push:
#    branches: [ master ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Description'
  
jobs:
  build:
    runs-on: windows-latest
    env:
      CSPROJ_FILE: src\KevinComponent.sln
    
    steps:
    - name: Load Repository Files
      uses: actions/checkout@v3
      
    - name: Install MSBuild
      uses: microsoft/setup-msbuild@v1.3.1
      with:
        vs-version: 22
        
      
    - name: Build KevinComponent.csproj
      run: msbuild.exe $CSPROJ_FILE /p:platform="Any CPU" /p:configuration="GitHub Release"
