name : Build And Publish to Nuget
on:
#   push:
#    branches: [ master ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Description'
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SOLUTION_FILE: src/KevinComponent.sln
      NUGET_FILE: src/KevinComponent/bin/GitHub Release/*.nupkg
    
    steps:    
    - name: Load Repository Files
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
        
    - name: Build Solution
      run: dotnet build $SOLUTION_FILE -c "GitHub Release"
      
    - name: Publish to nuget.org
      run: dotnet nuget push "$NUGET_FILE" --api-key ${{secrets.NUGET_API_KEY}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
    
    - name: Publish to GitHub Repository
      run: |
        dotnet nuget add source --username "soomin-kevin-sung" --password ${{secrets.ACCESS_TOKEN}} --store-password-in-clear-text --name "github" "https://nuget.pkg.github.com/soomin-kevin-sung/index.json"
        dotnet nuget push "$NUGET_FILE" --api-key ${{secrets.ACCESS_TOKEN}} --source "github" --skip-duplicate
