name : Build And Publish to Nuget
on:
#   push:
#    branches: [ master ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Description'
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Load Repository Files
      uses: actions/checkout@v3
      
    - name: Install MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Build KevinComponent.csproj
      run: msbuild.exe src\KevinComponent\KevinComponent.csproj /p:platform="Any CPU /p:configuration="Release"
    
